// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using e08.infrastructure;

#nullable disable

namespace e08.Migrations
{
    [DbContext(typeof(CountryTimeDBContext))]
    partial class CountryTimeDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("e08.domain.CityTime", b =>
                {
                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZone")
                        .HasColumnType("TEXT");

                    b.HasKey("City");

                    b.ToTable("CityTimes");
                });
#pragma warning restore 612, 618
        }
    }
}
